-- CLIENT
CREATE TABLE IF NOT EXISTS client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    client_type VARCHAR(20) NOT NULL,
    birth_date DATE,
    company_identifier VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- CONTRACT
CREATE TABLE IF NOT EXISTS contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    cost_amount NUMERIC(38,2) NOT NULL,
    update_date TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- FK (avec IF NOT EXISTS pris en charge par H2 2.x)
ALTER TABLE contract
    ADD CONSTRAINT IF NOT EXISTS fk_contract_client
        FOREIGN KEY (client_id) REFERENCES client(id);
